config/routes.rb
Rails.application.routes.draw do
	root "homes#fr_top"
 	get 'top' => 'homes#top', as: 'top'
  get 'about' => 'homes#about', as: 'about'

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	}
  resources :users, only: [:edit, :show, :update]
	get 'users/:id/leave' => 'users#leave', as: 'users_leave'
	put 'users/:id/hide' => 'users#hide', as: 'users_hide'
	get 'users/:id/my_reviews' => 'users#my_reviews', as: 'users_my_reviews'
	get 'users/:id/my_bookmarks' => 'users#my_bookmarks', as: 'users_my_bookmarks'

	get 'reviews/search' => 'reviews#search', as: 'reviews_search'
	get 'reviews/save_item/:itemCode' => 'reviews#save_item', as: 'save_item'
	get 'reviews/new/:itemCode' => 'reviews#new', as: 'reviews_new'
	resources :reviews, except: [:index, :new, :show] do
		resource :likes, only: [:create, :destroy]
	end

	# wants to include item_id in url
	post 'bookmarks/:item_id' => 'bookmarks#create', as: 'bookmarks_create'
	resources :bookmarks, only: :destroy

	get 'items/search' => 'items#search', as: 'items_search'
  get 'items/ranking' => 'items#ranking', as: 'items_ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 150}
	attachment :profile_photo
	attachment :background_photo

	# is_deletedカラムがtrueのuser（退会済）をはじく
  	def active_for_authentication?
    	super && (self.is_deleted == false)
  	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def reject_user
    @user = User.find_by(name: params[:user][:name].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:notice] = "このアカウントは退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:notice] = "入力されたユーザーネームまたはパスワードはアカウントと一致しません。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @bookmarks = Bookmark.where(user_id: current_user.id).limit(4).reverse_order
    @bookmarked_items = []
    @bookmarks.each do |bookmark|
      @bookmarked_items << RakutenWebService::Ichiba::Item.search(itemCode: bookmark.item.rakuten_item_id)
    end
    @reviews = Review.where(user_id: current_user.id).limit(4).reverse_order
    @items = []
    @reviews.each do |review|
      @items << RakutenWebService::Ichiba::Item.search(itemCode: review.item.rakuten_item_id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィール情報を編集しました。"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def leave
    @user = User.find(params[:id])
  end

  def hide
    @user = User.find(params[:id])
    #is_deletedカラムにフラグを立てる(defaultはfalse)
    @user.update(is_deleted: true)
    #ログアウトさせる
    reset_session
    flash[:notice] = "FitReviewsをご利用いただきまして誠にありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def my_reviews
    @user = User.find(params[:id])
    @reviews = Review.where(user_id: current_user.id).page(params[:page]).per(8).reverse_order
    @items = []
    @reviews.each do |review|
      @items << RakutenWebService::Ichiba::Item.search(itemCode: review.item.rakuten_item_id)
    end
  end

  def my_bookmarks
    @user = User.find(params[:id])
    @bookmarks = Bookmark.where(user_id: current_user.id).page(params[:page]).per(8).reverse_order
    @bookmarked_items = []
    @bookmarks.each do |bookmark|
      @bookmarked_items << RakutenWebService::Ichiba::Item.search(itemCode: bookmark.item.rakuten_item_id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :introduction, :profile_photo, :background_photo, :is_deleted)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all_bookmark.html.erb
<div class="u-width">
	<% if bookmarks.present? %>
		<% bookmarks.each_with_index do |bookmark,i| %>
			<% if bookmarked_items[i].first.present? %>
				<div class="item b-item">
					<div class="flex-parent-column">
						<div class="first-child" align="center">
							<% if bookmarked_items[i].first["mediumImageUrls"][0].present? %>
								<%= image_tag bookmarked_items[i].first["mediumImageUrls"][0] %>
							<% else %>
								この商品には商品画像がありません。
							<% end %>
						</div>
						<div class="second-child">
							<span class="flex-action" id="bookmark_<%= bookmark.item.id %>"><%= render 'bookmarks/bookmark', saved_item: bookmark.item %></span>
							<%= bookmarked_items[i].first["itemName"] %>
							<h5 class="item-price">価格: <%= number_with_delimiter(bookmarked_items[i].first["itemPrice"]) %>円</h5>
							<p><%= bookmarked_items[i].first['catchcopy'] %></p>
							<p><%= bookmarked_items[i].first['itemCaption'].truncate(120) %></p>
							<div class="flex-action">
								<%= link_to 'レビューを見る', save_item_path(bookmarked_items[i].first["itemCode"]), class:"btn review-btn" %>
								<%= link_to '楽天の購入ページへ', "#{bookmarked_items[i].first.url}", class:"btn rakuten-btn" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	<% else %>
		<div class="item b-item bottom-space">
			<p>ブックマークした商品はありません。<br>
			ブックマークした商品はこちらに表示されます。</p>
		</div>
	<% end %>
</div>

app/views/users/_all_reviews.html.erb
<div class="user-reviews u-width bottom-space">
  <% if reviews.present? %>
    <% reviews.each_with_index do |review,i| %>
      <% if items[i].first.present? %>
        <div class="user-review" id="reviews-<%= review.id %>">
          <div class="flex-parent-column border-b">
            <div class="first-child">
              <% if items[i].first["mediumImageUrls"][0].present? %>
                <%= image_tag items[i].first["mediumImageUrls"][0] %>
              <% else %>
                この商品には商品画像がありません。
              <% end %>
            </div>
            <div class="second-child">
              <%= link_to reviews_new_path(review.item.rakuten_item_id) do %>
                <%= items[i].first['itemName'] %>
              <% end %>
              <h5 class="item-price">価格: <%= number_with_delimiter(items[i].first["itemPrice"]) %>円</h5>
            </div>
          </div>
          <div class="flex-bet">
            <div>
              <%= attachment_image_tag review.user, :profile_photo, format: 'jpg', fallback: "user_no_image.png", size: "40x40", class:"profile-photo" %>
              <span class="user-name"><%= review.user.name %></span>
            </div>
            <div>
              <% if review.user == current_user %>
                <div class="dropdown">
                  <button class="btn dropdown-toggle dropdown-angle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="fas fa-angle-down"></i>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to edit_review_path(review), class:"btn" do %>
                        <i class="far fa-edit"> 編集</i>
                      <% end %>
                    </li>
                    <li><%= link_to review_path(review), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？", class:"btn" do %>
                        <i class="far fa-trash-alt"> 削除</i>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
          <div class="review-body">
            <span id="rated_<%= review.id %>"></span>
            <script>
              $('#rated_<%= review.id %>').raty({
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= review.rate %>,
              });
            </script>
            <div class="word-break">
              <%= review.body %>
            </div>
            <%= attachment_image_tag review, :item_image, class:"review-img" %>
            <div class="time-created"><%= review.created_at.to_s(:datetime_jp) %></div>
            <div class="border-top">
              <span id="like_<%= review.id %>">
              <%= render 'likes/like', review: review %></span>
            </div>
          </div>
        </div>
      <% else %>
        <div class="user-review">
          この商品は削除されました。
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="user-review bottom-space">
      <p>まだレビューを書いた商品がありません。<br>
      さっそくレビューを書いてみよう！</p>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container bottom-space">
	<div class="row">
		<%= form_for @user do |f| %>
			<div class="user-form">
				<%= link_to user_path(@user) do %>
					<p><i class="fas fa-chevron-left"></i> 保存せずに戻る</p>
				<% end %>
				<% if @user.errors.any? %>
					<div class="alert">
						<ul>
							<% @user.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<div class="form">
					<%=f.label :profile_photo, 'プロフィール画像を追加する' %>
					<div class="preview preview-profile-photo"></div>
					<%= f.attachment_field :profile_photo, class:"file" %>
				</div>
				<table>
					<tbody>
						<tr>
							<td><%= f.label :name, 'ユーザーネーム' %>
							<%= f.text_field :name, class:"user-input-field form-control" %></td>
						</tr>
						<tr>
							<td><%= f.label :introduction, '自己紹介' %>
							<%= f.text_area :introduction, class:"form-control", rows: "9", class:"user-input-field form-control" %></td>
						</tr>
						<tr>
							<td><%= f.label :email, "メールアドレス" %>
							<%= f.email_field :email, class:"user-input-field form-control" %></td>
						</tr>
						<tr>
							<td class="user-form-submit">
								<div>
									<%= f.submit "変更を保存する", class:"btn btn-sm btn-blue" %>
								</div>
								<div>
									<%= link_to '退会手続きに進む', users_leave_path(@user), class:"btn btn-sm btn-red" %>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		<% end %>
	</div>
</div>

app/views/users/leave.html.erb
<div class="container bottom-space">
	<div class="row bottom-space">
		<div class="deactive-account-form">
			<%= link_to edit_user_path(@user) do %>
				<p><i class="fas fa-chevron-left"></i> 戻る</p>
			<% end %>
			<ul class="list-group deactivate-account-form-list top-space ">
				<li class="list-group-item list-group-item-danger">退会申請</li>
				<li class="list-group-item">
					退会をされますと、この会員に関する全ての情報が削除されます。<br>
					本当に退会しますか？
					<div class="deactivate-account-btn">
						<% if user_signed_in? && @user.id == current_user.id %>
						    <%= link_to "退会する", users_hide_path(@user), method: :put, "data-confirm" => "退会申請を確定する。", class:"btn btn-sm btn-red" %>
						<% end %>
					</div>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/users/my_bookmarks.html.erb
<%= render 'homes/header' %>

<section class="top-space">
	<div class="u-width">
		<h4>ブックマークした商品一覧</h4>
	</div>
	<%= render 'all_bookmark', bookmarks: @bookmarks, bookmarked_items: @bookmarked_items %>
	<div align="center">
		<%= paginate @bookmarks %>
	</div>
</section>

 <style>
	.search_for_purchase {
		display: block;
	}
</style>

app/views/users/my_reviews.html.erb
<%= render 'homes/header' %>

<section class="top-space">
	<div class="u-width">
		<h4>レビューを書いた商品一覧</h4>
	</div>
	<%= render 'all_reviews', reviews: @reviews, items: @items %>
	<div align="center">
    <%= paginate @reviews %>
  </div>
</section>

app/views/users/show.html.erb
<%= render 'homes/header' %>

<section class="user-bio top-sm-space bottom-space">
	<div class="container">
		<div class="flash-notice">
			<%= flash[:notice] %>
	    </div>
	    <div class="flex-introduction">
			<%= attachment_image_tag @user, :profile_photo, format: 'jpg', fallback: "user_no_image.png", size: "60x60", class:"profile-photo" %>
			<div class="username-intro">
				<div><strong><%= @user.name %></strong></div>
				<p><%= @user.introduction %></p>
				<% if @user.id == current_user.id %>
					<%= link_to 'プロフィールを編集する', edit_user_path(@user) %>
				<% end %>
			</div>
			<ul class="list-group">
				<li class="list-group-item"><i class="fas fa-pen"></i> レビューを書いた数: <%= @user.reviews.count %></li>
				<li class="list-group-item"><i class="far fa-bookmark"></i> ブックマークした数: <%= @user.bookmarks.count %></li>
				<li class="list-group-item"><i class="far fa-grin-beam"></i> いいねをした数: <%= @user.likes.count %></li>
			</ul>
		</div>
	</div>
</section>

<div class="u-width">
	<ul class="nav nav-tabs" id="nav-tabs">
		<li role="presentation" class="active"><a>最近書いたレビュー</a></li>
		<li role="presentation"><a>ブックマークした商品</a></li>
	</ul>
</div>

<div class="top-space bottom-space hide-form" id="bookmarked-items">
	<%= link_to users_my_bookmarks_path(@user) do %>
		<div class="u-width">
			<h6 class="btn2"><i class="far fa-bookmark"></i> ブックマークした商品一覧</h6>
		</div>
	<% end %>
	<%= render 'all_bookmark', bookmarks: @bookmarks, bookmarked_items: @bookmarked_items %>
	<% if @user.bookmarks.count > 4 %>
		<div class="u-width top-space">
			<%= link_to users_my_bookmarks_path(@user) do %>
				<button class="see-more">もっと見る</button>
			<% end %>
		</div>
	<% end %>
</div>

<div class="top-space bottom-space show-form" id="reviewed-items">
	<%= link_to users_my_reviews_path(@user) do %>
		<div class="u-width">
			<h4 class="btn2"><i class="fas fa-pen"></i> レビューを書いた商品一覧</h4>
		</div>
	<% end %>
	<%= render 'all_reviews', reviews: @reviews, items: @items %>
	<% if @user.reviews.count > 4 %>
		<%= link_to users_my_reviews_path(@user) do %>
			<div class="u-width">
				<button class="see-more">もっと見る</button>
			</div>
		<% end %>
	<% end %>
</div>

<style>
	.search_for_purchase {
		display: block;
	}
</style>

<script>
const navTabs = document.getElementById('nav-tabs');
const tabs = navTabs.querySelectorAll('li');
const rItems = document.getElementById('reviewed-items');
const bItems = document.getElementById('bookmarked-items');

tabs[0].addEventListener('click', () => {
	tabs[0].classList.add('active');
	tabs[1].classList.remove('active');
	if (rItems.classList.contains('hide-form')) {
		rItems.classList.remove('hide-form');
		rItems.classList.add('show-form');
		bItems.classList.remove('show-form');
		bItems.classList.add('hide-form');
	}
});

tabs[1].addEventListener('click', () => {
	tabs[1].classList.add('active');
	tabs[0].classList.remove('active');
	if (bItems.classList.contains('hide-form')) {
		bItems.classList.remove('hide-form');
		bItems.classList.add('show-form');
		rItems.classList.remove('show-form');
		rItems.classList.add('hide-form');
	}
});
</script>