config/routes.rb
Rails.application.routes.draw do
	root "homes#fr_top"
 	get 'top' => 'homes#top', as: 'top'
  get 'about' => 'homes#about', as: 'about'

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	}
  resources :users, only: [:edit, :show, :update]
	get 'users/:id/leave' => 'users#leave', as: 'users_leave'
	put 'users/:id/hide' => 'users#hide', as: 'users_hide'
	get 'users/:id/my_reviews' => 'users#my_reviews', as: 'users_my_reviews'
	get 'users/:id/my_bookmarks' => 'users#my_bookmarks', as: 'users_my_bookmarks'

	get 'reviews/search' => 'reviews#search', as: 'reviews_search'
	get 'reviews/save_item/:itemCode' => 'reviews#save_item', as: 'save_item'
	get 'reviews/new/:itemCode' => 'reviews#new', as: 'reviews_new'
	resources :reviews, except: [:index, :new, :show] do
		resource :likes, only: [:create, :destroy]
	end

	# wants to include item_id in url
	post 'bookmarks/:item_id' => 'bookmarks#create', as: 'bookmarks_create'
	resources :bookmarks, only: :destroy

	get 'items/search' => 'items#search', as: 'items_search'
  get 'items/ranking' => 'items#ranking', as: 'items_ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def fr_top
    @rankings = Review.group(:item_id).select("reviews_item_id, average_rate").order('average_rate desc').average(:rate)
    @index = 0
    @reviews = Review.all.page(params[:page]).per(6).reverse_order
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_fr_header.html.erb
<nav class="navbar">
	<div class="navbar-left">
		<%= link_to 'FitReviews', root_path, class:"FitReviews-logo" %>
	</div>
	<div class="navbar-right">
		<% if user_signed_in? %>
			<div id="show-nav"><i class="fas fa-bars"></i></div>
			<ul id="nav-list">
				<li id="hide-nav"><i class="fas fa-times"></i></li>
				<li class="nav-user-info">
					<%= attachment_image_tag current_user, :profile_photo, format: 'jpg', fallback: "user_no_image.png", size: "60x60", class:"profile-photo" %>
					<p>ようこそ、<%= current_user.name %>さん</p></li>
				<li><%= link_to 'ランキング', items_ranking_path, class:"btn btn-sm nav-ranking-btn" %></li>
				<li><%= link_to 'レビューを書く', reviews_search_path, class:"btn btn-sm nav-btn" %></li>
				<li><%= link_to 'マイページ', user_path(current_user), class:"btn btn-sm nav-btn" %></li>
				<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-sm nav-btn" %></li>
			</ul>
		<% else%>
			<div id="show-nav"><i class="fas fa-bars"></i></div>
			<ul id="nav-list">
				<li id="hide-nav"><i class="fas fa-times"></i></li>
				<li></li>
				<li><%= link_to 'ランキング', items_ranking_path, class:"btn btn-sm nav-ranking-btn" %></li>
				<li><%= link_to 'レビューを書く', reviews_search_path, class:"btn btn-sm nav-btn" %></li>
				<li><%= link_to 'ログイン', new_user_session_path, class:"btn btn-sm nav-btn" %></li>
				<li><%= link_to 'サインアップ', new_user_registration_path, class:"btn btn-sm nav-btn" %></li>
			</ul>
		<% end %>
	</div>
</nav>

app/views/homes/_header.html.erb
<nav class="sticky-header navbar navbar-color">
	<div class="flex-nav nav-width">
		<div class="navbar-left">
			<%= link_to 'FitReviews', root_path, class:"FitReviews-logo-header" %>
		</div>
		<div class="nav-search">
			<div class="search_for_purchase">
				<!-- 購入したい商品を検索する -->
				<%= form_tag :items_search, method: :get do  %>
					<div class="header-search-flex">
							<div>
								<%= select_tag 'genreId', options_for_select({プロテイン: 567603, 栄養補助スナック: 566807, その他のサプリ: 563727, 筋トレ器具: 201865}, 567603), include_blank: false, class:"form-control header-select" %>
							</div>
							<div class="input-group header-search-nest">
								<%= text_field_tag 'keyword', params[:keyword], required: true, class:"form-control top-search-textfield" %>
								<span class="input-group-btn">
									<button type="submit" class="btn btn-default top-search-submit"><i class="fas fa-search"></i></button>
								</span>
							</div>
					</div>
				<% end %>
			</div>
			<div class="search_for_review">
				<!-- レビューする商品を検索する -->
				<%= form_tag :reviews_search, method: :get do  %>
					<div class="header-search-flex">
						<div>
								<%= select_tag 'genreId', options_for_select({プロテイン: 567603, 栄養補助スナック: 566807, その他のサプリ: 563727, 筋トレ器具: 201865}, 567603), include_blank: false, class:"form-control header-select" %>
						</div>
						<div class="input-group header-search-nest">
							<%= text_field_tag 'keyword', params[:keyword], required: true, class:"form-control top-search-textfield" %>
							<span class="input-group-btn">
								<button type="submit" class="btn btn-default top-search-submit"><i class="fas fa-search"></i></button>
							</span>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<div class="navbar-right">
			<% if user_signed_in? %>
				<div id="show-nav"><i class="fas fa-bars"></i></div>
				<ul id="nav-list">
					<li id="hide-nav"><i class="fas fa-times"></i></li>
					<li class="nav-user-info">
						<%= attachment_image_tag current_user, :profile_photo, format: 'jpg', fallback: "user_no_image.png", size: "60x60", class:"profile-photo" %>
						<p><%= current_user.name %>さん</p></li>
					<li><%= link_to 'ランキング', items_ranking_path, class:"btn btn-sm nav-ranking-btn" %></li>
					<li><%= link_to 'レビューを書く', reviews_search_path, class:"btn btn-sm nav-btn" %></li>
					<li><%= link_to 'マイページ', user_path(current_user), class:"btn btn-sm nav-btn" %></li>
					<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-sm nav-btn" %></li>
				</ul>
			<% else%>
				<div id="show-nav"><i class="fas fa-bars"></i></div>
				<ul id="nav-list">
					<li id="hide-nav"><i class="fas fa-times"></i></li>
					<li></li>
					<li><%= link_to 'ランキング', items_ranking_path, class:"btn btn-sm nav-ranking-btn" %></li>
					<li><%= link_to 'レビューを書く', reviews_search_path, class:"btn btn-sm nav-btn" %></li>
					<li><%= link_to 'ログイン', new_user_session_path, class:"btn btn-sm nav-btn" %></li>
					<li><%= link_to 'サインアップ', new_user_registration_path, class:"btn btn-sm nav-btn" %></li>
				</ul>
			<% end %>
		</div>
	</div>
</nav>

<style>
.search_for_purchase {
	display: none;
}
.search_for_review {
	display: none;
}
</style>

app/views/homes/about.html.erb
<%= render 'homes/header' %>

<section class="about-background">
	<div class="container">
		<div class="row">
			<div>
				<h1 class="how-to-use">FitReviwsのご利用方法。</h1>
				<p class="how-to-use-text">FitReviewsでフィットネス商品の口コミの投稿・閲覧することができます。</p>
			</div>
		</div>
	</div>
</section>

<section class="container top-space about-icons">
	<div>
		<%= image_tag asset_path('comment-icon.png'), class:"icon-image" %>
		<h2 class="about-rev">口コミ</h2>
		<p class="about-exp">プロテイン、栄養補助スナック、サプリメント、筋トレ器具など<br>
		フィットネスに欠かせない幅広い商品の口コミを掲載していきます。<br>
		どのプロテインやサプリメントが一番いいのか、またどれを<br>
		買えばいいのかというフィットネス界の永遠のテーマ。<br>
		そんな悩みを同じ筋トレまたは健康を気にしている仲間同士で<br>
		情報を共有し合うことができます。</p>
	</div>
	<div>
		<%= image_tag asset_path('protein-icon.png'), class:"icon-image" %>
		<h2 class="about-rank">ランキング</h2>
		<p class="about-exp">ユーザーの投稿の総合評価をもとにジャンル別ランキングを掲載しています。<br>
		人気の商品を見てフィットネス商品を選ぶ際の決めてになればと思います。<br>
		フィットネスを始めたけど何を買えばいいかわからないという方から、<br>
		より美味しく栄養パフォーマンスの良い商品などを求めている上級者まで<br>
		ご利用ください。</p>
		<p class="about-exp"><%= link_to 'ジャンル別ランキングへ', items_ranking_path %></p>
	</div>
</section>

<style>
	.search_for_purchase {
		display: block;
	}
</style>

app/views/homes/fr_top.html.erb
<%= render 'homes/header' %>

<div class="mv">
	<div class="container">
	  <div class="row">
		  <div class="flash-notice">
				<%= flash[:notice] %>
		  </div>
		</div>
	  <div class="row">
			<section>
				<%= form_tag :items_search, method: :get do  %>
					<div class="search-flex">
						<div>
							<%= select_tag 'genreId', options_for_select({プロテイン: 567603, 栄養補助スナック: 566807, その他のサプリ: 563727, 筋トレ器具: 201865}, 567603), include_blank: false, class:"form-control top-select" %>
						</div>
						<div class="input-group top-search-nest">
							<%= text_field_tag 'keyword', params[:keyword], placeholder:"プロテイン、プロテインバー...", required: true, class:"form-control top-search-textfield" %>
							<span class="input-group-btn">
								<button type="submit" class="btn btn-default top-search-submit"><i class="fas fa-search"></i></button>
							</span>
						</div>
					</div>
				<% end %>
			</section>
		</div>
	</div>
</div>

<div class="width-90">
  <section class="top-space">
    <%= render 'items/genres' %>
  </section>

  <section class="top-space">
    <%= render 'items/keywords' %>
  </section>

  <section class="top-space">
    <%= render 'items/recommended', rankings: @rankings %>
  </section>

  <section class="top-space">
    <%= render 'reviews/recent', reviews: @reviews %>
  </section>
</div>

app/views/homes/top.html.erb
<div class="container top-container">
	<div class="row top-row">
		<nav class="nav navbar-nav navbar-right">
			<div id="show-nav"><i class="fas fa-plus-square"></i></div>
			<ul id="top-nav-list">
				<li id="hide-nav"><i class="fas fa-minus-square"></i></li>
				<li><a class="btn btn-sm top-btn" href="#profile"><h4>Profile</h4></a></li>
				<li><a class="btn btn-sm top-btn" href="#skills"><h4>Skills</h4></a></li>
				<li><a class="btn btn-sm top-btn" href="#portfolio"><h4>Portfolio</h4></a></li>
				<li><a class="btn btn-sm top-btn" href="#contact"><h4>Contact</h4></a></li>
			</ul>
		</nav>
	</div>
	<!-- プロフィール -->
	<div class="row top-row">
		<div id="profile">
			<h1><i class="fas fa-user"> Profile</i></h1><br>
			<div class="top-flex">
				<div>
					<%= image_tag asset_path('Akihito_Otsuka.png'), id:"my-profile-pic" %>
				</div>
				<div class="my-introduction">
					<p class="line-h">はじめまして。大塚章仁と申します。<br>
						プロフィールを見ていただきありがとうございます。<br>
						私はアメリカの大学を2019年に卒業し、その後はプログラミングスクールに通いたいと思っていたので、プログラミングスクールの学費調達のためにアルバイト入社し勤めていました。<br>
						そして今年2020年にエンジニアになりたいという思いからDMM WEBCAMPというプログラミングスクールに3ヶ月通い、現在転職活動中です。
						また、転職活動をしながらドットインストールなどのプログラミング学習サイトを利用してプログラミングの勉強を毎日続けております。
						ページ下にポートフォリオのURLも記載しているので、是非一度見ていただけると幸いです。
						よろしくお願いいたします。</p>
				</div>
			</div>
		</div>
	</div>
	<!-- スキル -->
	<div class="row top-row">
		<div id="skills">
			<h1><i class="fas fa-lightbulb"> Skills</i></h1>
			<div class="skills-flex skills-list">
				<div>
					<h3><i class="fas fa-desktop"> プログラミング言語</i></h3>
					<h4>HTML</h4>
					<h4>CSS</h4>
					<h4>Ruby</h4>
					<h4>JavaScript</h4>
					<h4>jQuery</h4>
					<h3><i class="far fa-window-maximize"> フレームワーク</i></h3>
					<h4>Ruby on Rails</h4>
				</div>
				<div>
					<h3><i class="fas fa-box-open"> その他</i></h3>
					<h4>Git/GitHub</h4>
					<h4>Slack</h4>
					<h4>ZOOM</h4>
					<h4>Remo</h4>
					<h4>Trello</h4>
				</div>
			</div>
		</div>
	</div>
	<!-- ワーク -->
	<div class="row top-row">
		<div id="portfolio">
			<h1><i class="fas fa-briefcase"> Portfolio</i></h1>
			<div class="portfolio-list">
				<!-- FitReviewsへ -->
				<h3>ポートフォリオ名: FitReviews</h3>
				<h4><i class="fas fa-arrow-down"></i> (下の画像をクリック) <i class="fas fa-arrow-down"></i></h4>
				<%= link_to root_path do %>
					<%= image_tag asset_path('fr_top.png'), class:"portfolio-pic" %>
				<% end %>
				<div class="portfolio-info line-h" align="left">
					<h4><strong>GitHub:</strong></h4>
						<p><a href="https://github.com/akki1027/FitReviews">https://github.com/akki1027/FitReviews</a></p>
					<h4><strong>ポートフォリオ説明:</strong></h4>
						<p>FitReviwsはフィットネス商品の口コミサイトです。<br>
						ユーザーはフィットネスに関連する商品の口コミを投稿することができ、ユーザーの評価によるジャンル別ランキングを表示しています。<br>
						プロテイン、栄養補助スナック、サプリメント、筋トレ器具などフィットネスに欠かせない幅広い商品の口コミをシェアして、ユーザー同士が商品を選ぶ際の決めてになればと思います。</p>
					<h4><strong>主な利用シーン:</strong></h4>
						<p>どのプロテイン、栄養補助スナック、サプリメント、筋トレ器具などを買えばいいかわからない時が主な利用シーンになります。<br>
						フィットネスを始めたけどどのサプリメントがいいかわからない初心者の方から、より美味しい味や栄養価パフォーマンスの良い商品などを求めている上級者まで利用することができます。<br>
						また自分のオススメ商品の口コミを書くことで、他のユーザーの手助けになりたいと思う際にも利用することができます。</p>
					<h4><strong>テーマを選んだ理由:</strong></h4>
						<p>私はジムで週5日以上の筋トレを約8年間続けており、プロテインやサプリメントなどを購入する際にどれを買えばいいかと迷うことがよくありました。そしてどれを買えばいいかと悩んでも、決め手となるような口コミサイトがありませんでした（個人で自分のブログなどに紹介しているものしかない）。<br>
						どのプロテインやサプリメントが一番いいのか、またどれを買えばいいのかというのはフィットネス界の永遠のテーマでもあります。<br>
						そんな悩みを同じ筋トレまたは健康を気にしている仲間同士で情報を共有し合う場を提供し、購入する際の決めてとなればいいなという思いからこのテーマを選びました。</p>
					<h4><strong>ターゲットユーザー:</strong></h4>
						<p>
							・筋トレをされている方<br>
							・または健康を心掛けている方</p>
				</div>
			</div>
		</div>
	</div>
	<!-- お問い合わせ -->
	<div class="row top-row">
		<div id="contact">
			<h1><i class="fas fa-envelope"></i> Contact</h1>
			<h4>お問い合わせはこちらからよろしくお願いいたします。</h4>
			<address><a href="mailto:akki0127808@gmail.com">akki0127808@gmail.com</a></address>
		</div>
	</div>
</div>

<style>
footer {
	display: none;
}
</style>