config/routes.rb
Rails.application.routes.draw do
	root "homes#fr_top"
 	get 'top' => 'homes#top', as: 'top'
  get 'about' => 'homes#about', as: 'about'

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	}
  resources :users, only: [:edit, :show, :update]
	get 'users/:id/leave' => 'users#leave', as: 'users_leave'
	put 'users/:id/hide' => 'users#hide', as: 'users_hide'
	get 'users/:id/my_reviews' => 'users#my_reviews', as: 'users_my_reviews'
	get 'users/:id/my_bookmarks' => 'users#my_bookmarks', as: 'users_my_bookmarks'

	get 'reviews/search' => 'reviews#search', as: 'reviews_search'
	get 'reviews/save_item/:itemCode' => 'reviews#save_item', as: 'save_item'
	get 'reviews/new/:itemCode' => 'reviews#new', as: 'reviews_new'
	resources :reviews, except: [:index, :new, :show] do
		resource :likes, only: [:create, :destroy]
	end

	# wants to include item_id in url
	post 'bookmarks/:item_id' => 'bookmarks#create', as: 'bookmarks_create'
	resources :bookmarks, only: :destroy

	get 'items/search' => 'items#search', as: 'items_search'
  get 'items/ranking' => 'items#ranking', as: 'items_ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	validates :rakuten_item_id, uniqueness: true
	# validates :name, uniqueness: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
  	if params[:page]
      @page = params[:page].to_i
    else
      @page = 1
    end
    if params[:keyword] && params[:genreId]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword], genreId: params[:genreId]).page(params[:page])
      @keyword = params[:keyword]
      @genre_id = params[:genreId]
      @has_next_page = @items.has_next_page?
    elsif params[:genreId]
      @items = RakutenWebService::Ichiba::Item.search(genreId: params[:genreId]).page(params[:page])
      @genre_id = params[:genreId]
      @has_next_page = @items.has_next_page?
    end
  end

  def ranking
    if params[:genreId]
      @rankings = Review.joins(:item).where("items.rakuten_genre_id = ?", params[:genreId]).group(:item_id).select("reviews_item_id, average_rate").order('average_rate desc').average(:rate)
      @num = 1
      @genre = params[:genreId]
    else
      @rankings = Review.joins(:item).where("items.rakuten_genre_id = ?", 567603).group(:item_id).select("reviews_item_id, average_rate").order('average_rate desc').average(:rate)
      @num = 1
      @genre = "567603"
    end
    # @rankings = Review.group(:item_id).limit(5).select("reviews_item_id, average_rate").order('average_rate desc').average(:rate)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_genres.html.erb
<h4 class="title">ジャンルで探す</h4>
<div class="genres">
  <div>
    <%= link_to items_search_path(genreId: 567603) do %>
      <span class="genre-name">プロテイン</span>
      <%= image_tag asset_path('protein.jpg'), class:"genre-img" %>
    <% end %>
  </div>
  <div>
    <%= link_to items_search_path(genreId: 566807) do %>
      <span class="genre-name">栄養補助スナック</span>
      <%= image_tag asset_path('snack.jpg'), class:"genre-img" %>
    <% end %>
  </div>
  <div>
    <%= link_to items_search_path(genreId: 563727) do %>
      <span class="genre-name">サプリメント</span>
      <%= image_tag asset_path('supplement.jpg'), class:"genre-img" %>
    <% end %>
  </div>
  <div>
    <%= link_to items_search_path(genreId: 201865) do %>
      <span class="genre-name">筋トレ器具</span>
      <%= image_tag asset_path('equipment.jpg'), class:"genre-img" %>
    <% end %>
  </div>
</div>

app/views/items/_keywords.html.erb
<h4 class="title">キーワードで探す</h4>
<div class="keywords">
	<ul class="keyword-list">
		<li><%= link_to 'ホエイプロテイン', items_search_path(keyword: 'ホエイプロテイン', genreId: 567603) %></li>
		<li><%= link_to 'カゼインプロテイン', items_search_path(keyword: 'カゼインプロテイン', genreId: 567603) %></li>
		<li><%= link_to 'ソイプロテイン', items_search_path(keyword: 'ソイプロテイン', genreId: 567603) %></li>
		<li><%= link_to 'ウェイトゲイナー', items_search_path(keyword: 'ウェイトゲイナー', genreId: 567603) %></li>
		<li><%= link_to 'プロテインバー', items_search_path(keyword: 'プロテインバー', genreId: 566807) %></li>
		<li><%= link_to 'プロテインクッキー', items_search_path(keyword: 'プロテインクッキー', genreId: 566807) %></li>
		<li><%= link_to 'ナッツバー', items_search_path(keyword: 'ナッツバー', genreId: 566807) %></li>
		<li><%= link_to 'マルチビタミン',items_search_path(keyword: 'マルチビタミン', genreId: 563727) %></li>
		<li><%= link_to 'フィッシュオイル',items_search_path(keyword: 'フィッシュオイル', genreId: 563727) %></li>
		<li><%= link_to 'BCAA',items_search_path(keyword: 'BCAA', genreId: 563727) %></li>
		<li><%= link_to 'EAA',items_search_path(keyword: 'EAA', genreId: 563727) %></li>
		<li><%= link_to 'クレアチン',items_search_path(keyword: 'クレアチン', genreId: 563727) %></li>
		<li><%= link_to 'プレワークアウト',items_search_path(keyword: 'プレワークアウト', genreId: 563727) %></li>
		<li><%= link_to 'リストラップ',items_search_path(keyword: 'リストラップ', genreId: 201865) %></li>
		<li><%= link_to 'パワーグリップ',items_search_path(keyword: 'パワーグリップ', genreId: 201865) %></li>
		<li><%= link_to 'ダンベル',items_search_path(keyword: 'ダンベル', genreId: 201865) %></li>
		<li><%= link_to '可変式ダンベル',items_search_path(keyword: '可変式ダンベル', genreId: 201865) %></li>
		<li><%= link_to 'アブローラー',items_search_path(keyword: 'アブローラー', genreId: 201865) %></li>
		<li><%= link_to '腹筋台',items_search_path(keyword: '腹筋台', genreId: 201865) %></li>
		<li><%= link_to 'パワーラック',items_search_path(keyword: 'パワーラック', genreId: 201865) %></li>
		<li><%= link_to 'チューブ',items_search_path(keyword: 'チューブ', genreId: 201865) %></li>
		<li><%= link_to 'ストレッチローラー',items_search_path(keyword: 'ストレッチローラー', genreId: 201865) %></li>
		<li><%= link_to 'エアロバイク',items_search_path(keyword: 'エアロバイク', genreId: 201865) %></li>
	</ul>
</div>

app/views/items/_recommended.html.erb
<h4 class="title">総合おすすめ商品</h4>
<div class="flex-genre-link">
  <h4>ジャンル別ランキングはこちらから</h4>
  <h4><i class="fas fa-long-arrow-alt-right"></i> <%= link_to 'ジャンル別ランキング', items_ranking_path %></h4>
</div>

<div class="flex-recommended-item-tables">
  <% rankings.each do |item_id, rate, i| %>
    <% ranking = Item.find(item_id) %>
    <% item = RakutenWebService::Ichiba::Item.search(itemCode: ranking.rakuten_item_id) %>
    <!-- 楽天の商品は無くなることがあるため、なくなった商品は表示しない -->
    <% if item.first.present? %>
      <div class="recommended-item-table-layout">
        <table class="table-borderless recommended-item-table">
          <tbody>
            <tr>
              <td>
                <span class="overall-rec">総合オススメ</span>
              </td>
            </tr>
            <tr>
              <td>
                <span class="rate-star" id="ranking_<%= ranking.id %>"></span>
                  <script>
                    $('#ranking_<%= ranking.id %>').raty({
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: '<%= rate.to_d.to_s %>',
                    });
                  </script>
                  <%= rate.to_d.to_s %>
              </td>
            </tr>
            <tr align="center">
              <td>
                <% if item.first["mediumImageUrls"][0].present? %>
                  <%= image_tag item.first["mediumImageUrls"][0] %>
                <% else %>
                  この商品には商品画像がありません。
								<% end %>
              </td>
            </tr>
            <tr>
              <td><%= item.first["itemName"] %></td>
            </tr>
            <tr>
              <td class="item-price">価格: <%= number_with_delimiter(item.first["itemPrice"]) %>円</td>
            </tr>
            <tr>
              <td><%= link_to 'レビューを見る', save_item_path(item.first["itemCode"]), class:"btn m-review-btn" %>
                <%= link_to '楽天で購入', "#{item.first.url}", class:"btn m-rakuten-btn" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <% @index+= 1
        if @index == 4 then
        break
      end %>
    <% end %>
  <% end %>
</div>

app/views/items/ranking.html.erb
<%= render 'homes/header' %>

<div class="container">
	<% if @genre == "567603" %>
		<h4 class="rank-title"><i class="fas fa-crown"></i><strong> プロテインランキング</strong></h4>
	<% elsif @genre == "566807" %>
		<h4 class="rank-title"><i class="fas fa-crown"></i><strong> 栄養補助スナックランキング</strong></h4>
	<% elsif @genre == "563727" %>
		<h4 class="rank-title"><i class="fas fa-crown"></i><strong> その他のサプリランキング</strong></h4>
	<% elsif @genre == "201865" %>
		<h4 class="rank-title"><i class="fas fa-crown"></i><strong> 筋トレ器具ランキング</strong></h4>
	<% end %>
	<div align="center">
		<p>ジャンルを選択できます。</p>
		<%= form_tag :items_ranking, method: :get do  %>
			<%= select_tag 'genreId', options_for_select({プロテイン: 567603, 栄養補助スナック: 566807, その他のサプリ: 563727, 筋トレ器具: 201865}, 567603), include_blank: false, class:"form-control ranking-genre-select" %>
			<%= submit_tag "検索", :name => nil, class:"form-control ranking-submit" %>
		<% end %>
	</div>
</div>

<div class="container">
	<div class="row">
		<% if @rankings.present? %>
			<% @rankings.each do |item_id,rate,i| %>
				<% ranking = Item.find(item_id) %>
				<% item = RakutenWebService::Ichiba::Item.search(itemCode: ranking.rakuten_item_id) %>
				<% if item.first.present? %>
					<div class="rank-num">
						<%= @num %>位
					</div>
					<div class="item">
						<div class="flex-parent-column">
							<div class="first-child" align="center">
								<% if item.first["mediumImageUrls"][0].present? %>
									<%= image_tag item.first["mediumImageUrls"][0] %>
								<% else %>
									この商品には商品画像がありません。
								<% end %>
							</div>
							<div class="second-child">
								<span class="rate-star" id="ranking_<%= ranking.id %>"></span>
								<script>
									$('#ranking_<%= ranking.id %>').raty({
										starOff:  '<%= asset_path('star-off.png') %>',
										starOn : '<%= asset_path('star-on.png') %>',
										starHalf: '<%= asset_path('star-half.png') %>',
										half: true,
										readOnly: true,
										score: '<%= rate.to_d.to_s %>',
									});
								</script>
								<%= rate.to_d.to_s %><br>
								<%= item.first["itemName"] %><br>
								<h5 class="item-price">価格: <%= number_with_delimiter(item.first["itemPrice"]) %>円</h5>
								<p><%= item.first['catchcopy'] %></p>
								<div class="flex-action">
									<div class="rakuten-info">
										<p>楽天市場情報</p>
										<p>楽天市場での平均評価: <%= item.first['reviewAverage'].truncate(2) %></p>
										<p>楽天市場でのレビュー件数: (<%= item.first['reviewCount'] %>)</p>
									</div>
								</div>
								<div class="flex-action">
									<%= link_to 'レビューを見る', save_item_path(item.first["itemCode"]), class:"btn review-btn" %>
									<%= link_to '楽天の購入ページへ', "#{item.first.url}", class:"btn rakuten-btn" %>
								</div>
							</div>
						</div>
					</div>
					<% @num += 1
						if @num == 6 then
						break
						end %>
					<% end %>
			<% end %>
		<% else %>
			<p>このジャンルのレビューはまだありません。</p>
		<% end %>
	</div>
</div>

app/views/items/search.html.erb
<%= render 'homes/header' %>

<%= render 'reviews/search_by', genre_id: @genre_id, keyword: @keyword %>

<div class="search-results">
	<div class="flex-item-tables">
		<% if @items.present? %>
			<% @items.each do |item| %>
				<table class="table-borderless item-table">
					<tbody>
						<tr>
							<td>
								<% if item["mediumImageUrls"][0].present? %>
									<%= image_tag item["mediumImageUrls"][0] %>
								<% else %>
									この商品には商品画像がありません。
								<% end %>
							</td>
						</tr>
						<tr>
							<td><%= item["itemName"] %></td>
						</tr>
						<tr>
							<td class="item-price">価格: <%= number_with_delimiter(item["itemPrice"]) %>円</td>
						</tr>
						<tr>
							<td><%= link_to 'レビューを見る', save_item_path(item["itemCode"]), class:"btn m-review-btn" %>
								<%= link_to '楽天で購入', "#{item.url}", class:"btn m-rakuten-btn" %></td>
						</tr>
					</tbody>
				</table>
			<% end %>
		<% end %>
	</div>
	<div align="center">
		<ul class="pagination">
			<% unless @page == 1 %>
		    <li class="page-item"><%= link_to "前へ", controller: "items", action: "search", keyword: @keyword, page: @page - 1, genreId: @genre_id %></li>
		  <% end %>
		    <li class="page-item"><a class="page-link" href="#"><%= @page %></a></li>
		  <% if @has_next_page %>
		    <li class="page-item"><%= link_to "次へ", controller: "items", action: "search", keyword: @keyword, page: @page + 1, genreId: @genre_id %></li>
		  <% end %>
		</ul>
	</div>
</div>

<style>
	.search_for_purchase {
		display: block;
	}
</style>