config/routes.rb
Rails.application.routes.draw do
	root "homes#fr_top"
 	get 'top' => 'homes#top', as: 'top'
  get 'about' => 'homes#about', as: 'about'

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	}
  resources :users, only: [:edit, :show, :update]
	get 'users/:id/leave' => 'users#leave', as: 'users_leave'
	put 'users/:id/hide' => 'users#hide', as: 'users_hide'
	get 'users/:id/my_reviews' => 'users#my_reviews', as: 'users_my_reviews'
	get 'users/:id/my_bookmarks' => 'users#my_bookmarks', as: 'users_my_bookmarks'

	get 'reviews/search' => 'reviews#search', as: 'reviews_search'
	get 'reviews/save_item/:itemCode' => 'reviews#save_item', as: 'save_item'
	get 'reviews/new/:itemCode' => 'reviews#new', as: 'reviews_new'
	resources :reviews, except: [:index, :new, :show] do
		resource :likes, only: [:create, :destroy]
	end

	# wants to include item_id in url
	post 'bookmarks/:item_id' => 'bookmarks#create', as: 'bookmarks_create'
	resources :bookmarks, only: :destroy

	get 'items/search' => 'items#search', as: 'items_search'
  get 'items/ranking' => 'items#ranking', as: 'items_ranking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/ef1a52193c.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <!-- フッター -->
    <footer class="footer-background">
      <div class="container width-90-f">
        <div class="footer-flex">
          <div>
            <%= link_to 'FitReviews', root_path, class:"FitReviews-logo" %>
          </div>
          <div>
            <p class="about-title">About</p>
            <%= link_to 'FitReviewsについて', about_path, class:"btn footer-btn" %><br>
            <%= link_to '開発者プロフィール', top_path, class:"btn footer-btn" %><br>
            <a class="btn footer-btn" href="https://github.com/akki1027/FitReviews">GitHub</a>
          </div>
        </div>
        <div class="credit">
          <h5 class="copyright">Copyright ©︎ 2020 by FitReviews</h5>
          <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
          <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_22121.gif" border="0" alt="楽天ウェブサービスセンター" title="楽天ウェブサービスセンター" width="221" height="21"/></a>
          <!-- Rakuten Web Services Attribution Snippet TO HERE -->
        </div>
      </div>
    </footer>
    <!-- end -->
  </body>
</html>